# vim: syntax=python tabstop=4 expandtab
# coding: utf-8

__author__ = "Hanna Soderstrom"
__copyright__ = "Copyright 2022, Hanna Soderstrom"
__email__ = "hanna.soderstrom@gu.se"
__license__ = "GPL-3"

include: "rules/common.smk"
include: "rules/sentieon.smk"

report: "report/workflow.rst"


rule all:
    input:
        unpack(compile_output_list),


module prealignment:
    snakefile:
        github(
            "hydra-genetics/prealignment",
            path="workflow/Snakefile",
            tag="v0.2.0",
        )
    config:
        config


use rule * from prealignment as prealignment_*
